# Generated by Django 6.0.1 on 2026-01-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
    ]
