# Generated by Django 6.0.1 on 2026-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_saleline_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cash_deposit', 'Cash Deposit'), ('atm_cash', 'ATM Cash'), ('pos', 'POS'), ('card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('stripe', 'Stripe'), ('wise', 'Wise'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20),
        ),
    ]
