# Generated by Django 6.0.1 on 2026-01-28 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contract'),
        ('sales', '0004_alter_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.contract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gl_posted',
            field=models.BooleanField(default=False, help_text='Revenue recognized in GL'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('standard', 'Standard Invoice'), ('deposit', 'Deposit Invoice'), ('interim', 'Interim Invoice'), ('final', 'Final Invoice')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sales.sale'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('contract', 'invoice_type')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contract', 'invoice_type'], name='sales_invoi_contrac_e9eb81_idx'),
        ),
    ]
