# Generated by Django 4.2.7 on 2026-01-26 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_number', models.CharField(max_length=50, unique=True)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rental_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_refunded', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_late', models.BooleanField(default=False)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_reported', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='crm.client')),
            ],
            options={
                'ordering': ['-rental_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('perfect', 'Perfect Condition'), ('minor_damage', 'Minor Damage'), ('major_damage', 'Major Damage'), ('lost', 'Lost')], default='perfect', max_length=20)),
                ('damage_notes', models.TextField(blank=True)),
                ('damage_photos', models.CharField(blank=True, max_length=255, null=True)),
                ('cleaning_required', models.BooleanField(default=False)),
                ('cleaning_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('returned_by', models.CharField(blank=True, max_length=255)),
                ('received_by', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='rentals.rentalagreement')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('online', 'Online')], max_length=20)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rentalagreement')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rentalagreement')),
            ],
        ),
        migrations.CreateModel(
            name='RentalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currently_rented', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_maintenance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('damaged', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rental_days', models.IntegerField(default=0)),
                ('total_rental_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_inventory', to='inventory.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='rentalagreement',
            index=models.Index(fields=['client', 'status'], name='rentals_ren_client__4f2fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalagreement',
            index=models.Index(fields=['return_date'], name='rentals_ren_return__ab692c_idx'),
        ),
    ]
