# Generated by Django 4.2.7 on 2026-02-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('barcode_format', models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('qrcode', 'QR Code')], max_length=50)),
                ('width_mm', models.IntegerField(default=50)),
                ('height_mm', models.IntegerField(default=30)),
                ('include_product_name', models.BooleanField(default=True)),
                ('include_price', models.BooleanField(default=False)),
                ('include_date', models.BooleanField(default=False)),
                ('font_size', models.IntegerField(default=12)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('warehouse_location', models.CharField(blank=True, max_length=255)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('manufacture_date', models.DateField()),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='in_stock', max_length=50)),
                ('customer_reference', models.CharField(blank=True, max_length=100)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='barcodes.productbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('barcode_format', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcodes.barcodetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product_code', 'barcode_format')},
            },
        ),
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('scan_action', models.CharField(choices=[('receive', 'Receive'), ('pick', 'Pick'), ('pack', 'Pack'), ('ship', 'Ship'), ('sale', 'Sale'), ('return', 'Return'), ('inventory_check', 'Inventory Check')], max_length=100)),
                ('scanned_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['barcode', '-scan_date'], name='barcodes_ba_barcode_a7826e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label_number', models.CharField(max_length=50, unique=True)),
                ('batch_size', models.IntegerField(default=100, help_text='Number of labels in print batch')),
                ('print_date', models.DateField(auto_now_add=True)),
                ('printed_by', models.CharField(max_length=255)),
                ('quantity_printed', models.IntegerField()),
                ('quantity_used', models.IntegerField(default=0)),
                ('quantity_wasted', models.IntegerField(default=0)),
                ('product_barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodes.productbarcode')),
                ('template_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcodes.barcodetemplate')),
            ],
            options={
                'ordering': ['-print_date'],
            },
        ),
    ]
