# Generated by Django 6.0.1 on 2026-01-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeaccounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='expense_id',
            field=models.UUIDField(blank=True, help_text='Reference to accounting.Expense ID', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20),
        ),
    ]
