# Generated by Django 6.0.1 on 2026-01-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeaccounting', '0002_journalentry_expense_id_journalentry_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='financeacco_product_7ed17a_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='financeacco_movemen_91e51a_idx',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
