# Generated by Django 4.2.7 on 2026-01-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('fitting', 'Fitting'), ('measurement', 'Measurement'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('assigned_staff', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('client_type', models.CharField(choices=[('walk_in', 'Walk-in Customer'), ('regular', 'Regular Customer'), ('vip', 'VIP Customer'), ('bridal', 'Bridal Client'), ('corporate', 'Corporate')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rentals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('general_notes', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dress_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('measured_by', models.CharField(blank=True, max_length=255)),
                ('measured_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='crm.client')),
            ],
            options={
                'ordering': ['-measured_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_styles', models.CharField(blank=True, help_text='Comma-separated list of preferred styles', max_length=500)),
                ('favorite_colors', models.CharField(blank=True, max_length=500)),
                ('favorite_designers', models.CharField(blank=True, max_length=500)),
                ('preferred_fit', models.CharField(blank=True, max_length=100)),
                ('preferred_neckline', models.CharField(blank=True, max_length=100)),
                ('preferred_hemline', models.CharField(blank=True, max_length=100)),
                ('preferred_sleeve_type', models.CharField(blank=True, max_length=100)),
                ('preferred_fabrics', models.CharField(blank=True, max_length=500)),
                ('fabric_allergy', models.CharField(blank=True, max_length=255)),
                ('typical_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('follow_up', 'Follow-up'), ('interaction', 'Interaction'), ('complaint', 'Complaint'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('in_person', 'In Person'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.client')),
            ],
            options={
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='crm_client_email_3c7615_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type', 'status'], name='crm_client_client__ed8945_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='crm.client'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'status'], name='crm_appoint_client__83eaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date'], name='crm_appoint_schedul_87bbfe_idx'),
        ),
    ]
