# Generated by Django 6.0.1 on 2026-01-26 20:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0002_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('rental', 'Rental'), ('custom_sale', 'Custom-Made for Sale'), ('custom_rent', 'Custom-Made for Rental')], max_length=20)),
                ('product_specification', models.TextField(help_text='Detailed description of product/service')),
                ('contract_date', models.DateField()),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('production_start_date', models.DateField(blank=True, null=True)),
                ('production_end_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit_due_date', models.DateField(blank=True, null=True)),
                ('payment_schedule', models.JSONField(default=list, help_text="[{'date': '2026-02-01', 'amount': 5000, 'description': 'Milestone 1'}]")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_production', 'In Production'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('invoicing_started_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Custom contract terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='inventory.product')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_sold', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-contract_date'],
                'indexes': [models.Index(fields=['contract_number'], name='crm_contrac_contrac_c7fa5d_idx'), models.Index(fields=['client', 'status'], name='crm_contrac_client__f3badc_idx'), models.Index(fields=['contract_type'], name='crm_contrac_contrac_cac91b_idx')],
            },
        ),
    ]
