# Generated by Django 6.0.1 on 2026-01-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='color_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='customization_details',
            field=models.TextField(blank=True, help_text='Specific alterations, fitting notes, custom requests'),
        ),
        migrations.AddField(
            model_name='contract',
            name='damage_clause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='damage_liability',
            field=models.CharField(choices=[('none', 'No Liability'), ('partial', 'Partial Liability'), ('full', 'Full Liability')], default='partial', help_text='Customer liability for damage', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='design_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='design_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='design_notes',
            field=models.TextField(blank=True, help_text='Design specifications: style, silhouette, details, embellishments'),
        ),
        migrations.AddField(
            model_name='contract',
            name='design_reference',
            field=models.CharField(blank=True, help_text='Reference to design sketch, inspiration, or template', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='fabric_choice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='fabric_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity in meters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='late_return_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily penalty for late return', max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='measurements',
            field=models.JSONField(default=dict, help_text="{'bust': 92, 'waist': 78, 'hips': 98, 'length': 160}"),
        ),
        migrations.AddField(
            model_name='contract',
            name='revenue_schedule',
            field=models.JSONField(default=list, help_text="[{'milestone': 'deposit', 'date': '2026-02-01', 'amount': 5000, 'description': 'Deposit - design'}]"),
        ),
        migrations.AddField(
            model_name='contract',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deposit for rental (refundable)', max_digits=12),
        ),
    ]
