# Generated by Django 4.2.7 on 2026-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_date', models.DateField(unique=True)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('inactive_customers', models.IntegerField(default=0)),
                ('customer_lifetime_value_avg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('churn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI Card'), ('chart', 'Chart'), ('table', 'Table'), ('gauge', 'Gauge'), ('trend', 'Trend')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.CharField(blank=True, max_length=255)),
                ('metric_unit', models.CharField(blank=True, max_length=50)),
                ('data_source', models.CharField(max_length=255)),
                ('refresh_interval', models.IntegerField(default=300, help_text='Seconds')),
                ('widget_order', models.IntegerField(default=0)),
                ('column_span', models.IntegerField(default=1, help_text='Grid column span')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['widget_order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_date', models.DateField(unique=True)),
                ('total_items', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fast_moving', models.IntegerField(default=0)),
                ('slow_moving', models.IntegerField(default=0)),
                ('non_moving', models.IntegerField(default=0)),
                ('average_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_out_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('most_profitable_product', models.CharField(blank=True, max_length=255)),
                ('most_profitable_customer', models.CharField(blank=True, max_length=255)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('financial', 'Financial Report'), ('production', 'Production Report'), ('quality', 'Quality Report'), ('customer', 'Customer Report'), ('supplier', 'Supplier Report'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sql_query', models.TextField(blank=True, help_text='Custom SQL query for report')),
                ('include_fields', models.TextField(help_text='Comma-separated field names to include')),
                ('grouping', models.CharField(blank=True, max_length=255)),
                ('filtering', models.TextField(blank=True, help_text='JSON filter conditions')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_quantity', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('top_product', models.CharField(blank=True, max_length=255)),
                ('top_customer', models.CharField(blank=True, max_length=255)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('before_value', models.TextField(blank=True)),
                ('after_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_a_user_b11b71_idx'), models.Index(fields=['module', '-created_at'], name='analytics_a_module_73858b_idx')],
            },
        ),
    ]
