# Generated by Django 4.2.7 on 2026-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companysettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='allowed_extensions',
            field=models.CharField(default='pdf,docx,doc,xlsx,xls,html,txt', help_text='Comma separated list of allowed file extensions', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enforce_mime',
            field=models.BooleanField(default=True, help_text='Enforce content-based MIME/type checking on uploads'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='upload_max_size',
            field=models.BigIntegerField(default=5242880, help_text='Maximum upload size in bytes for document templates'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='use_s3',
            field=models.BooleanField(default=False, help_text='When enabled, documents are expected to use remote storage (S3)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='virus_scan',
            field=models.BooleanField(default=False, help_text='Enable virus scanning (requires ClamAV/clamd)'),
        ),
    ]
