# Generated by Django 4.2.7 on 2026-01-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysettings_allowed_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='auto_quarantine',
            field=models.BooleanField(default=True, help_text='Automatically quarantine (deactivate) infected document templates'),
        ),
    ]
