# Generated by Django 4.2.7 on 2026-02-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('defect_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_delivery_days', models.IntegerField(default=0)),
                ('price_competitiveness_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('responsiveness_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('overall_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('review_cycle_days', models.IntegerField(default=90)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Performance',
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_username', models.CharField(max_length=255, unique=True)),
                ('portal_password', models.CharField(max_length=255)),
                ('is_portal_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email_for_notifications', models.EmailField(max_length=254)),
                ('notify_pending_payments', models.BooleanField(default=True)),
                ('notify_invoice_receipt', models.BooleanField(default=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_portal', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payment Portal',
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('po_confirmation', 'PO Confirmation'), ('delivery_note', 'Delivery Note'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='supplier_documents/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('items_count', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('discrepancy', 'Discrepancy'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_matches', to='suppliers.purchaseordertracking')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'unique_together': {('po', 'invoice_number')},
            },
        ),
    ]
