# Generated by Django 6.0.1 on 2026-01-26 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contract'),
        ('inventory', '0002_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ready_made', 'Ready-Made'), ('custom_made', 'Custom-Made'), ('rental_asset', 'Rental Asset')], default='ready_made', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_on_order',
            field=models.IntegerField(default=0, help_text='Awaiting production', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_reserved',
            field=models.IntegerField(default=0, help_text='Reserved for rentals', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='RentalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active (Out with customer)'), ('returned', 'Returned')], default='reserved', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_reservations', to='crm.contract')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_reservations', to='inventory.product')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rental_start_date'],
                'indexes': [models.Index(fields=['contract', 'status'], name='inventory_r_contrac_72fdc8_idx'), models.Index(fields=['product', 'rental_start_date', 'rental_end_date'], name='inventory_r_product_ef4eaa_idx')],
                'unique_together': {('product', 'contract')},
            },
        ),
    ]
