# Generated by Django 6.0.1 on 2026-01-28 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_product_type_product_quantity_on_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='balance_after',
            field=models.IntegerField(default=0, help_text='Stock quantity after this movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='balance_before',
            field=models.IntegerField(default=0, help_text='Stock quantity before this movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Locked after creation, prevents edits'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='locked_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_number',
            field=models.CharField(db_index=True, default='PENDING', editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('rental', 'Rental'), ('return', 'Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sale'), ('rental', 'Rental'), ('return', 'Rental Return'), ('adjustment', 'Stock Adjustment'), ('damage', 'Damage/Loss'), ('transfer', 'Transfer Between Warehouses')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_number'], name='inventory_s_movemen_0f2675_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_number'], name='inventory_s_referen_79719e_idx'),
        ),
    ]
