# Generated by Django 6.0.1 on 2026-01-28 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice Template'), ('contract', 'Contract Template'), ('receipt', 'Receipt Template'), ('purchase_order', 'Purchase Order Template'), ('delivery_note', 'Delivery Note Template')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='HTML/Template content')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('master_service', 'Master Service Agreement'), ('rental', 'Rental Agreement'), ('custom_design', 'Custom Design Agreement'), ('supplier', 'Supplier Agreement'), ('employment', 'Employment Contract')], default='master_service', max_length=50)),
                ('includes_payment_terms', models.BooleanField(default=True)),
                ('includes_liability', models.BooleanField(default=True)),
                ('includes_confidentiality', models.BooleanField(default=True)),
                ('includes_termination', models.BooleanField(default=True)),
                ('includes_dispute_resolution', models.BooleanField(default=True)),
                ('company_name_required', models.BooleanField(default=True)),
                ('client_name_required', models.BooleanField(default=True)),
                ('date_fields_required', models.BooleanField(default=True)),
                ('amount_fields_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_template', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('invoice_number_format', models.CharField(default='{prefix}{year}-{sequence}', help_text='Format: {prefix}{year}-{sequence}', max_length=50)),
                ('show_po_number', models.BooleanField(default=True)),
                ('show_tax', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('show_notes', models.BooleanField(default=True)),
                ('show_terms', models.BooleanField(default=True)),
                ('company_logo_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('hidden', 'Hidden')], default='top_left', max_length=20)),
                ('color_scheme', models.CharField(default='blue', help_text='Primary color theme', max_length=50)),
                ('font_family', models.CharField(default='Arial', help_text='Base font for template', max_length=50)),
                ('payment_terms_text', models.TextField(default='Net 30', help_text='Default payment terms text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_template', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('generate', 'Generated Document'), ('customize', 'Customized')], max_length=20)),
                ('document_reference', models.CharField(blank=True, help_text='Invoice/Contract ID etc', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='documents.documenttemplate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Usage Log',
                'verbose_name_plural': 'Template Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='documents_d_templat_e7a2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['is_default', 'template_type'], name='documents_d_is_defa_52203a_idx'),
        ),
    ]
