# Generated by Django 6.0.1 on 2026-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('doc', 'Word Document'), ('xlsx', 'Excel'), ('xls', 'Excel'), ('html', 'HTML'), ('txt', 'Text'), ('other', 'Other')], default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Upload your invoice/contract file (PDF, Word, etc.)', null=True, upload_to='templates/files/'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=models.TextField(blank=True, help_text='HTML/Template content'),
        ),
    ]
