# Generated by Django 4.2.7 on 2026-01-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttemplate_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='scan_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], db_index=True, default='unknown', help_text='Current virus scan status for uploaded template files', max_length=20),
        ),
        migrations.CreateModel(
            name='TemplateScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task id when scanned asynchronously', max_length=255)),
                ('scanned_by', models.CharField(blank=True, help_text='Who/what triggered scan (e.g., worker id)', max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Template Scan Log',
                'verbose_name_plural': 'Template Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
