# Generated by Django 4.2.7 on 2026-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttemplate_scan_status_templatescanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='quarantine_reason',
            field=models.TextField(blank=True, help_text='Reason or message recorded when the template was quarantined (e.g., scan result)'),
        ),
    ]
