# Generated by Django 6.0.1 on 2026-01-28 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_expense_options_expense_approved_at_and_more'),
        ('crm', '0003_add_design_revenue_rental_fields'),
        ('sales', '0005_invoice_contract_invoice_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredRevenueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferred_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recognized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recognized', models.BooleanField(default=False)),
                ('recognized_at', models.DateField(blank=True, null=True)),
                ('milestone_description', models.CharField(max_length=255)),
                ('milestone_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_revenue', to='crm.contract')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
                ('liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenue_liabilities', to='accounting.chartofaccounts')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenue_recognitions', to='accounting.chartofaccounts')),
            ],
            options={
                'ordering': ['milestone_date'],
                'unique_together': {('contract', 'milestone_description')},
            },
        ),
        migrations.CreateModel(
            name='RevenueRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('recognition_date', models.DateField()),
                ('recognition_type', models.CharField(choices=[('deposit_received', 'Deposit Received (Liability)'), ('interim_progress', 'Interim Progress Recognition'), ('final_revenue', 'Final Revenue Recognition'), ('direct_sale', 'Direct Sale Revenue'), ('rental_income', 'Rental Income'), ('reversal', 'Reversal Entry')], max_length=30)),
                ('recognized_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_recognitions', to='crm.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_recognitions', to='sales.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_recognitions', to='accounting.journalentry')),
                ('offset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_offset_entries', to='accounting.chartofaccounts')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_recognitions', to='accounting.chartofaccounts')),
            ],
            options={
                'ordering': ['-recognition_date'],
                'indexes': [models.Index(fields=['log_number'], name='accounting__log_num_af50a0_idx'), models.Index(fields=['recognition_date'], name='accounting__recogni_533920_idx'), models.Index(fields=['invoice'], name='accounting__invoice_318b49_idx'), models.Index(fields=['contract'], name='accounting__contrac_884707_idx')],
            },
        ),
    ]
