# Generated by Django 6.0.1 on 2026-01-28 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_revenue_recognition_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GLIntegrityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True, db_index=True)),
                ('total_debits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_balanced', models.BooleanField(default=False)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, help_text='Debits - Credits (should be 0)', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('check_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('issues_found', models.IntegerField(default=0, help_text='Number of unbalanced entries found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_integrity_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GL Integrity Check',
                'verbose_name_plural': 'GL Integrity Checks',
                'ordering': ['-check_date', '-created_at'],
                'indexes': [models.Index(fields=['-check_date'], name='accounting__check_d_b79c34_idx'), models.Index(fields=['is_balanced'], name='accounting__is_bala_15ae49_idx')],
            },
        ),
    ]
