# Generated by Django 4.2.7 on 2026-02-01 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('inventory', '0005_product_created_by_product_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('parameter', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('acceptance_criteria', models.TextField()),
                ('check_type', models.CharField(choices=[('visual', 'Visual'), ('measurement', 'Measurement'), ('functional', 'Functional'), ('destructive', 'Destructive')], max_length=20)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_date', models.DateField()),
                ('total_inspections', models.IntegerField(default=0)),
                ('total_units_inspected', models.IntegerField(default=0)),
                ('total_units_passed', models.IntegerField(default=0)),
                ('total_defects', models.IntegerField(default=0)),
                ('critical_defects', models.IntegerField(default=0)),
                ('major_defects', models.IntegerField(default=0)),
                ('minor_defects', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-period_date'],
                'unique_together': {('period', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='QualityChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inspection_stage', models.CharField(choices=[('incoming', 'Incoming Materials'), ('in_process', 'In-Process'), ('final', 'Final Inspection')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_templates', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('inspection_number', models.CharField(max_length=50, unique=True)),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspection_date', models.DateTimeField()),
                ('units_inspected', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('units_passed', models.IntegerField(default=0)),
                ('units_failed', models.IntegerField(default=0)),
                ('units_rework', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.workorderstage')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.qualitychecklisttemplate')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], max_length=20)),
                ('actual_value', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.checklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.inspectionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('defect_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('color', 'Color Issue'), ('seam_quality', 'Seam Quality'), ('measurement', 'Measurement'), ('fabric_defect', 'Fabric Defect'), ('stitch_defect', 'Stitch Defect'), ('trim', 'Trim Issue'), ('finish', 'Finish Issue'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=20)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('action_taken_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.inspectionrecord')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='production.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.qualitychecklisttemplate'),
        ),
    ]
